# Generated by Django 3.2.4 on 2022-03-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0005_remove_student_random_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.student')),
                ('random_id', models.CharField(default=None, max_length=8, null=True)),
            ],
        ),
    ]
