# Generated by Django 3.2.4 on 2022-03-24 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipsbase', '0002_alter_studentid_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentID',
            new_name='RandomID',
        ),
        migrations.RenameField(
            model_name='randomid',
            old_name='student',
            new_name='ruser',
        ),
    ]
