# Generated by Django 3.2.4 on 2022-03-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_delete_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='random_id',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
