# Generated by Django 3.2.4 on 2022-03-26 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_ipaddress_randomid'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPadd_RanID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(default=None, max_length=8, null=True)),
                ('ipaddress', models.GenericIPAddressField(null=True)),
                ('ruser', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='randomid',
            name='ruser',
        ),
        migrations.DeleteModel(
            name='IPaddress',
        ),
        migrations.DeleteModel(
            name='RandomID',
        ),
    ]
