# Generated by Django 3.2.4 on 2022-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_student_random_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='random_id',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
