# Generated by Django 3.2.4 on 2022-03-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_student_random_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='random_id',
        ),
    ]
